/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as LearningPathRouteImport } from './routes/learning-path'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as CertificateSlugRouteImport } from './routes/certificate.$slug'
import { Route as CoursesSlugWatchRouteImport } from './routes/courses/$slug.watch'

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathRoute = LearningPathRouteImport.update({
  id: '/learning-path',
  path: '/learning-path',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateSlugRoute = CertificateSlugRouteImport.update({
  id: '/certificate/$slug',
  path: '/certificate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugWatchRoute = CoursesSlugWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => CoursesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learning-path': typeof LearningPathRoute
  '/playground': typeof PlaygroundRoute
  '/quiz': typeof QuizRoute
  '/tutor': typeof TutorRoute
  '/certificate/$slug': typeof CertificateSlugRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/courses/$slug/watch': typeof CoursesSlugWatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learning-path': typeof LearningPathRoute
  '/playground': typeof PlaygroundRoute
  '/quiz': typeof QuizRoute
  '/tutor': typeof TutorRoute
  '/certificate/$slug': typeof CertificateSlugRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/courses': typeof CoursesIndexRoute
  '/courses/$slug/watch': typeof CoursesSlugWatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learning-path': typeof LearningPathRoute
  '/playground': typeof PlaygroundRoute
  '/quiz': typeof QuizRoute
  '/tutor': typeof TutorRoute
  '/certificate/$slug': typeof CertificateSlugRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/courses/$slug/watch': typeof CoursesSlugWatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/learning-path'
    | '/playground'
    | '/quiz'
    | '/tutor'
    | '/certificate/$slug'
    | '/courses/$slug'
    | '/courses/'
    | '/courses/$slug/watch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/learning-path'
    | '/playground'
    | '/quiz'
    | '/tutor'
    | '/certificate/$slug'
    | '/courses/$slug'
    | '/courses'
    | '/courses/$slug/watch'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/learning-path'
    | '/playground'
    | '/quiz'
    | '/tutor'
    | '/certificate/$slug'
    | '/courses/$slug'
    | '/courses/'
    | '/courses/$slug/watch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LearningPathRoute: typeof LearningPathRoute
  PlaygroundRoute: typeof PlaygroundRoute
  QuizRoute: typeof QuizRoute
  TutorRoute: typeof TutorRoute
  CertificateSlugRoute: typeof CertificateSlugRoute
  CoursesSlugRoute: typeof CoursesSlugRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-path': {
      id: '/learning-path'
      path: '/learning-path'
      fullPath: '/learning-path'
      preLoaderRoute: typeof LearningPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$slug': {
      id: '/certificate/$slug'
      path: '/certificate/$slug'
      fullPath: '/certificate/$slug'
      preLoaderRoute: typeof CertificateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug/watch': {
      id: '/courses/$slug/watch'
      path: '/watch'
      fullPath: '/courses/$slug/watch'
      preLoaderRoute: typeof CoursesSlugWatchRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
  }
}

interface CoursesSlugRouteChildren {
  CoursesSlugWatchRoute: typeof CoursesSlugWatchRoute
}

const CoursesSlugRouteChildren: CoursesSlugRouteChildren = {
  CoursesSlugWatchRoute: CoursesSlugWatchRoute,
}

const CoursesSlugRouteWithChildren = CoursesSlugRoute._addFileChildren(
  CoursesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LearningPathRoute: LearningPathRoute,
  PlaygroundRoute: PlaygroundRoute,
  QuizRoute: QuizRoute,
  TutorRoute: TutorRoute,
  CertificateSlugRoute: CertificateSlugRoute,
  CoursesSlugRoute: CoursesSlugRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
